AllCops:
  Exclude:
    - vendor/**/*

Style/AndOr:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent
